### ISSUE TITLE
Version Nummer broken in 0.6.5

### ISSUE THREAD

**Issue by MaikC76** [FalcoGer/CoordinateConverter#4]
I have the latest version installed but when I click on "Check for Updates" it tells me that I am using 0.5.16 and 0.6.5 is available.
I also think it would be good if the version number were displayed somewhere.

**Comment by FalcoGer** [comment]
@MaikC76 I just tested both the manual release.zip as well as the installer option, and both say that the current version is 0.6.5 and up to date. Is the menu entry for AH-64/DTC available for you? If not, you are indeed using an old version.

![image](https://github.com/FalcoGer/CoordinateConverter/assets/16250196/0de2e87e-0f62-46cd-ab57-422467752f5d)

Try deleting the old version before reinstalling or overwrite the files with the ones from `release.zip`.

**Comment by MaikC76** [comment]
I have no idea what I did wrong on the first try. I have now downloaded it again and made sure that I unpacked the correct one. Now I also have version 0.6.5.
How about you just call it release_0.6.5.zip instead of release.zip ;-) Then you will know which version you have downloaded.
I didn't get around to it today. I'll test the whole tool tomorrow.
Thanks for your work.

**Comment by FalcoGer** [comment]
@MaikC76 

The version will now display in the title bar.
Also I changed the github actions to have the files under release include the version.
