### ISSUE TITLE
Apache radio preset frequencies don't save

### ISSUE THREAD

**Issue by Stains02** [FalcoGer/CoordinateConverter#5]
I have found that the state of the checkboxes on the Apache radio preset tabs don't seem to save state. I'll checkmark one and go to another tab or preset and come back and they're unchecked.

![image](https://github.com/FalcoGer/CoordinateConverter/assets/157631061/c83c2d21-45b5-4d9c-8ff4-9b30cbc5360e)

**Comment by FalcoGer** [comment]
Old version. Get the latest version and if the bug is still present, please provide a step by step guide to reproduce the issue. Also include the expected behavior and what actually happens.

**Comment by Stains02** [comment]
I have the latest version. I just used screenshots from your YouTube to show the problem. I need to figure out how to do a screen recording to demonstrate the issue.

**Comment by jamesamckenzie** [comment]
Here's a video to better demonstrate my issue. I am using the latest DCS Open Beta (as of 1/27/24) and Coordinate Converter version 0.6.8.

https://youtu.be/607zIFYwj4Y

**Comment by FalcoGer** [comment]
you can use obs. or you can just tell me what you click in which order.

**Comment by Stains02** [comment]
Here's a video describing my issue:

https://youtu.be/R9SlmIvQ-hw

DCS 2.9.2.49940
Coordinate Converter v0.6.8

**Comment by FalcoGer** [comment]
Should be fixed.

**Comment by Stains02** [comment]
That worked. Thank you!!
