### ISSUE TITLE
A-10CII Waypoint Names

### ISSUE THREAD

**Issue by Stains02** [FalcoGer/CoordinateConverter#6]
When importing waypoints in the A-10CII, each waypoint name has M01, M02, M03, etc appended to the beginning of the waypoint name. Also, spaces in waypoint names (which the aircraft does allow) don't seem to make the jump from CoordinateConverter to DCS. Not a big deal, but would be nice.

**Comment by FalcoGer** [comment]
The waypoint names are intentional, because the A10 doesn't allow the same name for different points. It also doesn't allow numbers to be at the beginning of the name and it puts an M in front if you try.
The numbering allows to quickly look for the point in the CDU.

The spaces will be fixed.

**Comment by FalcoGer** [comment]
Spaces should now be added for the A10
