### ISSUE TITLE
[BUG] - *AH-64D - Points, CM Fixed Arty and Fixed Wing are inverted*

### ISSUE THREAD

**Issue by flanker0ne** [FalcoGer/CoordinateConverter#8]
**Describe the bug**
- [x] I am using the latest version of the software, available on the [release page](https://github.com/FalcoGer/CoordinateConverter/releases/latest)

As you can see in the screenshot, to get the Artyllery Icon (EF) I have to set the property Fixed Wing in the menù
Btw, great App, keep up the good work!!

**To Reproduce**

**Expected behavior**

**Screenshots**
![immagine](https://github.com/FalcoGer/CoordinateConverter/assets/105388387/5d945907-9056-4189-b2e5-24e840a7e132)

**Versions:**
- Coordinate converter: v0.6.10
- DCS: 2.X.Y

**Additional context**

**Comment by FalcoGer** [comment]
Thank you.
This has been fixed.
