### ISSUE TITLE
Update to README.md

### ISSUE THREAD

**Issue by kkernan** [FalcoGer/CoordinateConverter#9]
There is a broken link in the README.md to an installation.txt file that doesn't seem to exist anymore.

Might be nice if there were build instructions. I'm having a hard time getting it to build in rider at the moment.

**Comment by FalcoGer** [comment]
I fixed the link. Thank you.

I don't know how to use you IDE. You will require the CoordinateSharp and Newtonsoft libraries.
If you just want to use it, go to the [releases page](https://github.com/FalcoGer/CoordinateConverter/releases/latest) and download the latest version.

**Comment by kkernan** [comment]
I figured it out, it was ide related. I wanted to build it because I'm interested in perhaps doing some dcs programming myself, am familiar with .net, and I like the way this program works. I've been using it and love it, very cool app. Thanks for sharing.
